# Default Configuration

spring:
    profiles:
        active: dev

    main:
        banner-mode: "off"

    jersey:
        servlet:
            load-on-startup: 1

server:
    port: 8000
    error:
        include-stacktrace: never
        whitelabel:
            enabled: false
        include-exception: false
    servlet:
        context-path: /
    compression:
        enabled: true

wchallenge:
    jsonplacehoder:
        url: "https://jsonplaceholder.typicode.com"

---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production
