# Default Configuration

spring:
    profiles:
        active: dev

    main:
        banner-mode: "off"

    jersey:
        servlet:
            load-on-startup: 1

    flyway:
        locations: "classpath:db/migrations"

    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                show_sql: false
                format_sql: false
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false

server:
    port: 8000
    error:
        include-stacktrace: never
        whitelabel:
            enabled: false
        include-exception: false
    servlet:
        context-path: /
    compression:
        enabled: true

wchallenge:
    jsonplacehoder:
        url: "https://jsonplaceholder.typicode.com"

---
# Configuration for Development Environment

spring:
    profiles:
        - dev
        - development

    datasource:
        url: jdbc:postgresql://localhost:5432/wchallenge
        username: wchallenge
        password: wchallenge

    jpa:
        properties:
            hibernate:
                format_sql: true

logging:
    level:
        com.github.juanmbellini.wchallenge: DEBUG
        org.hibernate.SQL: DEBUG
        root: INFO

---
# Configuration for Staging Environment

spring:
    profiles:
        - staging

logging:
    level:
        com.github.juanmbellini.wchallenge: DEBUG
        org.hibernate.SQL: DEBUG
        root: INFO

---
# Configuration for Production Environment

spring:
    profiles:
        - prod
        - production

logging:
    level:
        root: WARN